apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-template-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-template
  template:
    metadata:
      labels:
        app: auth-template
    spec:
      containers:
      - name: auth-template
        image: nginx:latest
        ports:
        - containerPort: 80