version: '3'
services:
  app:
    build: ./app
    ports:
      - "5555:5555"
    volumes:
      - ./app:/app 
      - /app/node_modules
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "3307:3306"
